name: Publish

on:
  push:
    tags:
      - "[0-9]*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ICU libraries
        run: sudo apt-get install -y libicu-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install build dependencies
        run: pip install build twine

      - name: Build
        run: python -m build

      - name: Publish to GitHub Packages
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: twine upload --repository-url https://pypi.pkg.github.com/whatsnowplaying/ dist/*
